// This file is generated by `npm run codegen`.
import * as migration0_20201209T192431UsersTable from './2020.12.09T19.24.31.users-table'
import * as migration1_20201209T192509RolesTable from './2020.12.09T19.25.09.roles-table'

export const migrations = {
  "./2020.12.09T19.24.31.users-table": migration0_20201209T192431UsersTable,
  "./2020.12.09T19.25.09.roles-table": migration1_20201209T192509RolesTable
}
