sudo: required
dist: trusty

language: node_js

node_js:
  - '4'
  - '5'

env:
  - SEQUELIZE=^1.0.0
  - SEQUELIZE=^2.0.0
  - SEQUELIZE=^3.0.0

before_script:
  - npm install sequelize@$(echo $SEQUELIZE)

script:
  - "npm test"

notifications:
  irc:
    - "chat.freenode.net#sequelizejs"
