sudo: false

language: node_js

node_js:
  - '6'
  - '8'
  - '10'
  - '11'

cache: npm

env:
  - SEQUELIZE=^3.0.0
  - SEQUELIZE=^4.0.0

before_script:
  - npm i sequelize@$(echo $SEQUELIZE)
  - npm run build

script:
  - npm run lint
  - npm test
