language: node_js

jobs:
  include:
  - node_js: '10'
    env: SEQUELIZE=5
  - node_js: '10'
    env: SEQUELIZE=next

before_script:
  - npm i sequelize@$(echo $SEQUELIZE)

script:
  - npm run lint
  - npm test
