import {readdirSync, writeFileSync} from 'node:fs'

const migrationsDir = new URL('./migrations/', import.meta.url)

const migrations = readdirSync(migrationsDir)
  .filter(file => file.endsWith('.ts') && file !== 'barrel.ts')
  .sort()
  .map((file, index) => {
    const modulePath = `./${file.slice(0, -'.ts'.length)}`
    return {
      identifier: `migration${index}_${toIdentifierSuffix(modulePath)}`,
      modulePath,
    }
  })

const imports = migrations.map(migration => {
  return `import * as ${migration.identifier} from '${migration.modulePath}'`
})

const entries = migrations.map(migration => {
  return `  "${migration.modulePath}": ${migration.identifier}`
})

writeFileSync(
  new URL('./barrel.ts', migrationsDir),
  [
    '// This file is generated by `npm run codegen`.',
    ...imports,
    '',
    'export const migrations = {',
    entries.join(',\n'),
    '}',
    '',
  ].join('\n'),
)

function toIdentifierSuffix(modulePath) {
  return modulePath
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(' ')
    .map(part => `${part[0].toUpperCase()}${part.slice(1)}`)
    .join('')
}
