name: pkg.pr.new
on:
  pull_request: {}
  push:
    branches: [main, deps, pkg.pr.new]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g corepack@0.31.0 # todo: delete if https://github.com/nodejs/corepack/issues/612 is resolved
      - run: corepack enable
      - run: pnpm install
      - run: pnpm build
      - run: pnpm pkg-pr-new publish
